### ISSUE TITLE
usb.core.USBError: [Errno 32] Pipe error

### ISSUE THREAD

**Issue by petergerten** [Parrot-Developers/sequoia-ptpy#21]
Trying the example, I can successful get the device info but then get "usb.core.USBError: [Errno 32] Pipe error" when camera.initiate_capture() is executed. Any hints what might go wrong there?

**Comment by petergerten** [comment]
closed. a vendor specific auth requirement was missing.

**Comment by deanand** [comment]
Can you elaborate please? I'm getting this same error.

**Comment by domenzain** [comment]
This happens when PTPy is waiting for an answer that never comes.
Essentially the camera stops responding beyond libUSB's timeout.

You can activate all debug info with `PTPY_DEBUG=1` in the environment, and save it to a file with `PTPY_DEBUG_LOG=debug.log`. Additionally you can follow pyusb instructions for even more low-level details.
