### ISSUE TITLE
Release USB 

### ISSUE THREAD

**Issue by AlexisPotvin** [Parrot-Developers/sequoia-ptpy#6]
There is no "clean" way to stop the usb connection without a shutdown!
It would be great if we were able to release the usb interface when deleting the PTPy class. 
From what i have seen there is no real proper way to release the usb interface.

**Comment by domenzain** [comment]
You can call the `__shutdown` method on the PTPy instance.
This means a "shutdown" of the class rather than a shutdown of the camera.

Note that it is possible to ask the physical shutdown of the camera through PTP as well... With the operation `power_down` using the same terminology as the PTP standard. 

This will probably change in the future and will be dealt with automatically.

**Comment by domenzain** [comment]
Looking at the current implementation, I find that either a normal `exit` of the Python program or an explicit call to the PTPy instance's `_shutdown` will result in the expected behaviour regarding USB release...

Is there another use case you had in mind?
Or a specific platform where this is not working?

**Comment by AlexisPotvin** [comment]
Well what i was trying to do was controlling the sequoia with multiple PTP implementation. The transfer implementation of PTPy for photo transfer is super slow so i wanted to use an other program to fetch the pictures.  But i figured out a way to do it! and yes the shutdown method is working to release the usd interface. I would just include it in the class destructor so on the event of the the __del__ method called it will still be possible to claim the udb again without closing the program.

**Comment by domenzain** [comment]
I think it is dangerous to leave that to `__del__`.
As that will get called upon garbage collection.
And depending on the Python implementation that could happen right after `del PTPy_instance`, at the very end of the Python interpreter session, or anywhere in between... But `PTPy_instance._shutdown()` will be immediate.

I have tried locally and this will only rarely behave as expected. I think it's best to add that to the `README` as a known quirk.

**Comment by domenzain** [comment]
Sequoia also has FTP implemented over RNDIS.
Though it will be less clear which files correspond to which capture. This shouldn't be a problem if you don't have some very finicky characterisation set-up to begin with.
Since it is a different set of USB endpoints you can probably use it at the same time without having to release USB.
